# Generated by Django 3.2.21 on 2023-10-23 22:14

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('bio', models.CharField(help_text='Enter a brief bio', max_length=140)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', help_text='Image must be a square', max_length=255, verbose_name='image')),
                ('specialization', models.CharField(choices=[('recreational', 'Recreational'), ('freestyle', 'Freestyle'), ('dance', 'Dance'), ('pairs', 'Pairs')], default='recreational', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default='1', help_text='Enter a positive integer.')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('lesson_start', models.DateTimeField(help_text='Date: YYYY-MM-DD Time: HH:MM:SS')),
                ('lesson_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.DurationField(default='01:00:00', help_text='Format HH:MM:SS')),
                ('location', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_coach', to='roller_criu_app.coach')),
                ('likes', models.ManyToManyField(blank=True, related_name='lesson_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson_start'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='roller_criu_app.lesson')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_reserved', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('approved', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved')], default='pending', max_length=12)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='roller_criu_app.lesson')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
